{
    "name": "Website Conditioners",
    "summary": "Сайт-визитка ПрофиМонтаж: монтаж и электромонтаж",
    "version": "18.0.1.2.3",
    "sequence": -999,
    "category": "Website",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["website", "website_crm", "crm"],
    "data": [
        "security/ir.model.access.csv",
        "security/conditioners_review_security.xml",
        "security/conditioners_portfolio_security.xml",
        "security/conditioners_service_security.xml",
        "security/conditioners_faq_security.xml",
        "data/website_crm_form.xml",
        "data/website_menu.xml",
        "data/website_menu_cleanup.xml",
        "data/conditioners_service_data.xml",
        "data/conditioners_faq_data.xml",
        "templates/layout.xml",
        "templates/reviews.xml",
        "templates/portfolio.xml",
        "templates/services.xml",
        "templates/faq.xml",
        "data/website_contact_cleanup.xml",
        "data/website_pages.xml",
        "views/conditioners_review_views.xml",
        "views/conditioners_portfolio_views.xml",
        "views/conditioners_service_views.xml",
        "views/conditioners_faq_views.xml",
        "views/snippets.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "website_conditioners/static/src/scss/primary_variables.scss",
        ],
        "web.assets_backend": [
            "website_conditioners/static/src/js/portfolio_upload.js",
        ],
        "web.assets_frontend": [
            "website_conditioners/static/src/scss/conditioners.scss",
            "website_conditioners/static/src/js/portfolio_lightbox.js",
        ],
    },
    "installable": True,
    "application": True,
}
